### ISSUE TITLE
Overlap list check

### ISSUE THREAD

**Issue by Dev-hoon** [KIMCOYG/vanillaJS#4]
중복 되는 리스트 체크 후 들어가지 못하도록 막아야 함
![image](https://user-images.githubusercontent.com/22619283/72034882-a83bba00-32d9-11ea-9896-858525cb97f7.png)
위와 같이 대소문자 다른 경우도 중복으로 인식되어야 함.
HELLO 와 Hello 는 다른것

**Comment by KIMCOYG** [comment]
대소문자 구분 아직 안됨
